# Generated by Django 6.0.3 on 2026-03-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
