# Generated by Django 6.0.3 on 2026-03-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_user_profile_image_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
