# Generated by Django 6.0.3 on 2026-03-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follower',
            field=models.CharField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.CharField(default=0),
        ),
    ]
