# Generated by Django 6.0.3 on 2026-03-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_user_follower_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logedin',
            field=models.BooleanField(default=False, verbose_name='Logged In'),
        ),
    ]
