# Generated by Django 6.0.3 on 2026-03-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logedin',
        ),
    ]
