# Generated by Django 6.0.3 on 2026-03-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_user_logedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follower',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='user_followers', to='home.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='reqsend',
            field=models.ManyToManyField(blank=True, related_name='requests_sent', to='home.user'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='user_following', to='home.user'),
        ),
    ]
