# Generated by Django 6.0.3 on 2026-03-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_user_follower_user_followers_user_reqsend_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reqsend',
            new_name='requests',
        ),
    ]
