# Generated by Django 6.0.3 on 2026-03-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_reqsend_user_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.TextField(default='hello'),
        ),
    ]
