# Generated by Django 6.0.3 on 2026-03-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, null=True),
        ),
    ]
